spring:
  application:
    name: mystore-catalog
  profiles:
    default: local

server:
  #  port:
  shutdown: graceful
  compression:
    enabled: true

logging:
  level:
    root: info

zigzag:
  service_name: service-catalog-ux
  server:
    catalog:
      url: "http://catalog.service.alpha.zigzag.kr:9142"