spring:
  application:
    name: mystore-catalog
  profiles:
    default: local

server:
  #  port:
  shutdown: graceful
  compression:
    enabled: true

logging:
  level:
    root: info

dgs:
  graphql:
    schema-locations:
      - "classpath*:mystore-catalog.graphqls"
    graphiql:
      enabled: true
    path: /graphql/**

sentry:
  stacktrace:
    app.packages: "com.croquis.mystore"


zigzag:
  service_name: service-catalog-ux
  server:
    catalog:
      url: "http://catalog.service.alpha.zigzag.kr:9142"